package com.metro.model;

import java.io.Serializable;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Carasel")
public class Carasel implements Serializable {

	private int id;
	private int order;
	private String name;
	private List<Integer> images;
	
	
    
	

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public int getId() {
		return id;
	}



	public void setId(int id) {
		this.id = id;
	}



	public String getName() {
		return name;
	}



	@DynamoDBAttribute
	public void setName(String name) {
		this.name = name;
	}



	@DynamoDBAttribute
	public int getOrder() {
		return order;
	}



	public void setOrder(int order) {
		this.order = order;
	}




	@DynamoDBAttribute
	public List<Integer> getImages() {
		return images;
	}



	public void setImages(List<Integer> images) {
		this.images = images;
	}


	
	
	
	
}
