package com.metro.model;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "ImageModel")
public class ImageModel implements Serializable {

	private int id;
	private int order;
	private String name;
	private String m_url;
	
	
    
	

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public int getId() {
		return id;
	}



	public void setId(int id) {
		this.id = id;
	}



	public String getName() {
		return name;
	}



	@DynamoDBAttribute
	public void setName(String name) {
		this.name = name;
	}



	@DynamoDBAttribute
	public String getM_url() {
		return m_url;
	}



	public void setM_url(String m_url) {
		this.m_url = m_url;
	}



	@DynamoDBAttribute
	public int getOrder() {
		return order;
	}



	public void setOrder(int order) {
		this.order = order;
	}


	
	
	
}
